### PR TITLE
maintenance: update & fix CI, bump python >=3.8, bump postgresql >= 12

### PR DESCRIPTION
**Pull request by dmsimard**
- Bump Fedora 36 to 39
- Use cloud images for centos stream 8 and 9

### CODE REVIEW

**Comment by dmsimard** [comment]
recheck

**Comment by dmsimard** [comment]
There's now a failure about the python version of centos stream 8:
image

This should be addressed by this PR from @Thulium-Drake: https://github.com/ansible-community/ara-collection/pull/70

I will cherry-pick it here in the interest of trying to fix every job before merging this one PR.

**Comment by dmsimard** [comment]
We're missing python39-devel for centos stream 8:
Screenshot from 2024-02-10 20-22-34

and our version of postgresql is now not high enough:
Screenshot from 2024-02-10 20-22-43

**Comment by dmsimard** [comment]
re: postgresql, this is as a result of bumping django up to the latest LTS (4.2) in [ara 1.7.0](https://github.com/ansible-community/ara/releases/tag/1.7.0): https://docs.djangoproject.com/en/5.0/releases/4.2/#dropped-support-for-postgresql-11
image

**Comment by dmsimard** [comment]
Progress! Success everywhere but with postgresql:
Screenshot from 2024-02-10 20-22-43

Indeed, with django 4.2 (latest LTS):
Screenshot from 2024-02-10 20-40-35

**Comment by dmsimard** [comment]
It works!

I've squashed/cleaned up commits and I'll merge this soon.

@Thulium-Drake @hille721: FYI if you would like to look. 

We'll be able to close https://github.com/ansible-community/ara-collection/pull/70 and start looking at the other PRs which we'll need to rebase on top of latest master so they have those fixes.

**Comment by dmsimard** [comment]
It looks like the jobs may be race-y due to the nature of running multiple nodes, let me try that again.

**Comment by dmsimard** [comment]
recheck

**Comment by dmsimard** [comment]
> It looks like the jobs may be race-y due to the nature of running multiple nodes, let me try that again.

There are some assumptions in ara's integration tests that assume the test playbook is only ran once from localhost but here we have multiple nodes running concurrently (centos stream 8, 9 and fedora 39) in order to parallelize the test coverage across multiple distros.

That's where we would add the debian/ubuntu nodes if we had them.

We could fix the assumptions in the tests but I expect it is possible to continue running into "interesting" concurrency issues.

I need some time to think about the best approach that would be reliable and allow for the inclusion of debian and ubuntu.

**Comment by Thulium-Drake** [comment]
Would it be a start, at least for now, to drop the parallel testing of multiple ARA instances? I really can't think of a scenario where that's used, unless I'm missing something. Do you?

Also, how much I like (and run!) Debian, I think that's easier to add later and test when CI is alive again :-)

**Comment by dmsimard** [comment]
> Would it be a start, at least for now, to drop the parallel testing of multiple ARA instances? I really can't think of a scenario where that's used, unless I'm missing something. Do you?

Once upon a time, the idea was to test multiple distros inside a single job (instead of one job per distro) but we can do it the other way around, too. We've migrated around different Zuul instances over the years and now we have a more constrained set of images to work with: https://ansible.softwarefactory-project.io/zuul/labels
 
> Also, how much I like (and run!) Debian, I think that's easier to add later and test when CI is alive again :-)

Yes, I want to be able to test the distros that the collection pretends supporting :p

**Comment by dmsimard** [comment]
recheck

**Comment by dmsimard** [comment]
Not sure why that Zuul failure occurred, the repo has not moved. Amended last commit to trgger a new run.

**Comment by Thulium-Drake** [comment]
:rocket: Zuul's happy! Can we merge this? I'm starting to run into some issues for which there's already some PRs out :-) I'll happily integrate them when this is merged

**Comment by dmsimard** [comment]
> 🚀 Zuul's happy! Can we merge this? I'm starting to run into some issues for which there's already some PRs out :-) I'll happily integrate them when this is merged

Yes, this has been dragging on for too long. We can address the Zuul flappiness later.

Let's do it.

**Pull request merged**
