### PR TITLE
Added Cronjobs for keeping ARA clean

### LINKED ISSUE #6: ara_api role should setup a cron for "ara expire" and "ara playbook prune"
See: https://ara.readthedocs.io/en/latest/cli.html#ara-playbook-prune

The role should be able to set up a cron that runs the ``ara playbook prune`` command in order to keep the database tidy.

### PR DESCRIPTION
**Pull request by Thulium-Drake**
Fixes #6

### CODE REVIEW

**Comment by Thulium-Drake** [comment]
Hmm, something went wrong there :-)

**Comment by Thulium-Drake** [comment]
@dmsimard ping :-)

**Comment by Thulium-Drake** [comment]
Submitted here: https://review.opendev.org/c/recordsansible/ara-collection/+/773407

**Comment by dmsimard** [comment]
@Thulium-Drake I replied in the review for it, thanks !

**Pull request closed without merging**
