### PR TITLE
This should make SELinux transaction idempotent

### PR DESCRIPTION
**Pull request by Thulium-Drake**
I took a stab to make the SELinux related transactions idempotent, so only compile the module if the source file has changed and only loading it when A it is not loaded or B the source file changed

Not yet tested, but this should do it :)

### CODE REVIEW

**Comment by Thulium-Drake** [comment]
:tada:

**Comment by Thulium-Drake** [comment]
@dmsimard Ping! :-)

**Comment by dmsimard** [comment]
I must have missed the ping :sweat_smile:

This would be nice indeed.
I'm going to try and fix the CI and we can rebase this PR.

**Comment by dmsimard** [comment]
@Thulium-Drake could you please rebase on top of latest master ?

**Comment by dmsimard** [comment]
LGTM, thanks !

**Pull request merged**
