### PR TITLE
Add integration test for `api_(cert|key|ca)` options

### PR DESCRIPTION
**Pull request by devon-mar**
This PR:
- modifies the existing NGINX test to use `api_ca` instead of `api_insecure`
- adds a test with NGINX and client certificates

Related: https://github.com/ansible-community/ara/pull/392

### CODE REVIEW

**Comment by dmsimard** [comment]
Hi and thanks for the PR!

I was signing up to do the work but I am grateful that you kickstarted it :)

The CI is apparently broken, it needs to be updated.. part of it was https://github.com/ansible-community/ara-collection/pull/51 but it's been long enough that even that is out of date. I'll work something out.

**Comment by dmsimard** [comment]
I've managed to fix the CI jobs in https://github.com/ansible-community/ara-collection/pull/51 and it should merge soon.

**Comment by dmsimard** [comment]
@devon-mar this is a good first try at it.

I can help you carry it over the finish line if you are interested but I don't mind taking over either (and crediting you for the work) since I originally planned on doing it.

We'll need to rebase your patch on top of the CI fixes and I think we can figure out a way to re-use the existing nginx job to test the client CA.

Then, Zuul also has a special [Depends-On](https://zuul-ci.org/docs/zuul/latest/gating.html#cross-project-dependencies) feature that will allow us to test both this PR and [ara's PR](https://github.com/ansible-community/ara/pull/392) together without merging anything -- in a nutshell, Zuul will check out that PR and install that instead of the master branch.

Let me know o/

**Comment by devon-mar** [comment]
@dmsimard Sorry, I didn't see that you signed up for the work.

Feel free to take over this PR or make a new one. Let me know if you need any help!

**Comment by dmsimard** [comment]
> @dmsimard Sorry, I didn't see that you signed up for the work.
> 
> Feel free to take over this PR or make a new one. Let me know if you need any help!

No problem, I didn't want to put too much burden on your end if I could help it :)

I've gone ahead a submitted another PR with a few changes and I've decided to keep it as a separate job for now: https://github.com/ansible-community/ara-collection/pull/57

**Comment by dmsimard** [comment]
I'll close this PR, let's follow up in the other one. Feel free to review my changes and let me know if it looks good !

**Pull request closed without merging**
